"""Render a ScoreResult as a client-facing PDF (and matching JSON)."""
from __future__ import annotations

import os
from dataclasses import asdict
from datetime import UTC, datetime
from pathlib import Path

# ponytail: WeasyPrint needs Pango/GObject DLLs from MSYS2. Point it at the
# default install location if the caller hasn't set this themselves already;
# upgrade to reading it from a config file if the default path ever varies.
os.environ.setdefault("WEASYPRINT_DLL_DIRECTORIES", r"C:\msys64\mingw64\bin")

from jinja2 import Environment, FileSystemLoader
from weasyprint import HTML

from dpdp_analyzer.rules import Rule
from dpdp_analyzer.scoring import ScoreResult

DISCLAIMER = (
    "This report is generated by an automated tool and is not legal advice. "
    "Verify findings against the current DPDP Act and Rules before acting on them."
)

TEMPLATE_DIR = Path(__file__).parent.parent / "reports" / "templates"


def _build_context(score_result: ScoreResult, rules: list[Rule]) -> dict:
    rules_by_id = {rule.id: rule for rule in rules}
    remediation = [
        {
            "rule_id": item.rule_id,
            "category": item.category,
            "severity": item.severity,
            "section_ref": item.section_ref,
            "affected_rows": item.affected_rows,
            "description": rules_by_id[item.rule_id].description,
            "remediation": rules_by_id[item.rule_id].remediation,
        }
        for item in score_result.remediation
    ]
    return {
        "title": "DPDP Gap Analysis Report",
        "generated_on": datetime.now(tz=UTC).date().isoformat(),
        "overall_score": score_result.overall_score,
        "categories": [asdict(c) for c in score_result.categories],
        "remediation": remediation,
        "disclaimer": DISCLAIMER,
    }


def render_html(score_result: ScoreResult, rules: list[Rule]) -> str:
    context = _build_context(score_result, rules)
    env = Environment(loader=FileSystemLoader(TEMPLATE_DIR), autoescape=True)
    return env.get_template("report.html.j2").render(**context)


def render_report(score_result: ScoreResult, rules: list[Rule], out_path: str | Path) -> None:
    HTML(string=render_html(score_result, rules)).write_pdf(str(out_path))


def render_report_json(score_result: ScoreResult, rules: list[Rule]) -> dict:
    return _build_context(score_result, rules)
